apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ PROJECTNAME }}
  namespace: {{ NAMESPACE }}
  annotations:
   kubernetes.io/ingress.class: {{ KONGINGRESS }}
#    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
  - host: {{ KONGHOST }}
    http:
      paths:
      - backend:
          serviceName: {{ PROJECTNAME }}
          servicePort: 8080
        path: /{{ PROJECTNAME }}
  tls:
  - hosts:
    - {{ KONGHOST }}
